name: My First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      
    - name: Welcome Message
      run: echo "My First Github Actions."

    - name: List Files
      run: ls

    - name: Check if README.md exists
      id: check_readme
      run: |
        if [ -f README.md ]; then
          echo "README.md exists"
        else
          echo "README.md does not exist"
          exit 1
        fi

    - name: Read File
      if: steps.check_readme.outcome == 'success'
      run: cat README
